### ISSUE TITLE
Logic to ensure users enter correctly formatted search parameters

### ISSUE THREAD

**Issue by keithrutler** [Cascadia-Connections/gybitg#21]
User search box entries need to have valid data entered to be able to search the database. When incorrect characters are entered, an error will be shown next to the entry box with a description of what is allowed to be entered.

DOD - All search entries have required data type requirements and error messages showing the user what characters are allowed to be entered.

**Comment by Bansenauer-Cascadia** [comment]
Keith - in the future, please make the assignments for your issue cards, so it's clear they are yours

**Comment by keithrutler** [comment]
I apologize about not assigning it myself, several of our group's WiFi was cutting out at the end of class and Adam's WiFi was still working, and offered to assign me to the card from his account.
