### ISSUE TITLE
Require HS grad date

### ISSUE THREAD

**Issue by ksdurg** [Cascadia-Connections/gybitg#84]
Currently the HS graduation date for an athlete user profile is not required, so if it is not entered but searched for at a later date, then it crashes the app.  DoD when HS grad date is required for athlete user profile.

**Comment by keithrutler** [comment]
Changed assignee from Kevin to myself. Issue is related to my previous Input Validation Issue cards, but the Date variables were being reworked in the models from Datetime to String, so I had to skip this validation earlier while Alex made the Date changes.

**Comment by keithrutler** [comment]
DoD met, the HS grad date now has proper input validation and is required.
